// Generated by scripts/assemble-operator-dist.mjs — do not edit manually.
export const BUNDLED_BUILD_COMMIT_SHA = "8f1be8122a8ba788ad57858d5b94e55706fd0e03";
export const BUNDLED_BUILD_TIMESTAMP = "2026-07-10T10:29:53.054Z";
export const BUNDLED_APP_VERSION = "0.1.0";
