// Generated by scripts/assemble-operator-dist.mjs — do not edit manually.
export const BUNDLED_BUILD_COMMIT_SHA = "72e7f1e863babf70522fcba254a302d8f3ad0259";
export const BUNDLED_BUILD_TIMESTAMP = "2026-07-10T10:14:51.258Z";
export const BUNDLED_APP_VERSION = "0.1.0";
