// `Env` is generated by `wrangler types` (npm run cf-typegen) from wrangler.jsonc

// into worker-configuration.d.ts — do not hand-write the binding shape here.

import { assertBeaconOnStartup } from "../msh-ops/beacon/loadBeacon";
import { ensureAgentGovernance } from "../msh-ops/agent/initAgentGovernance";

import { CATALOG_ITEMS } from "./catalogData";

import { handleAuthRoute } from "./auth";

import { handleEngineRoute } from "./engine";

import { handleBuildInfoRoute } from "./buildInfo";

import { enforceOperatorApiAuth } from "./apiAuth";

import { handleWebhookRoute } from "./webhookTrigger";

import { handleSecurityRoute } from "./security";

import { handleTtxRoute } from "./ttx";

import { edgeAuthGate, handleOperatorAuth, handleOperatorSession } from "./edge/gate";

import { injectSecurityHeaders } from "./edge/headers";

import { handleFedGradeRoute } from "./fedgrade";

import { handleMarketplaceEdgeRoute } from "./marketplaceEdge";

import { handleHsxEdgeRoute } from "./hsxEdge";

import type { WorkerEnv } from "./env";

import { proxyLabel, resolveSurfaceMode, routeStorefrontSurface } from "./surface";
import { redirectToCanonicalEntry } from "./canonical";

import type { BackboneEnv } from "./backboneEnv";
import {
  GovernanceDO,
  handleGovernanceRoute,
  handleMarketplaceBackboneRoute,
  MarketplaceDO,
  SessionDO,
} from "./backbone";
import { handleGhostRoute } from "./ghost";
import { handleHealthRoute } from "./health";
import {
  enforceCockpitSession,
  enforceGovernancePolicy,
  enforceMarketplaceGovernance,
  handleKernelRoute,
  resolveEffectiveKernelContext,
} from "./kernel";
import { blockAutonomousInBeta } from "./mode";
import { handleTelemetryRoute, recordTelemetrySample } from "./telemetry";
import { handleUsageRoute } from "./usage";
import { handleFlowEventRoute } from "./flowRoute";
import { handleFlowIntelligenceRoute } from "./flowIntelligenceRoute";
import { handleBehaviorIntelligenceRoute } from "./behaviorRoute";
import { handleExperimentationRoute } from "./experimentationRoute";
import { handleTrafficActivationRoute } from "./trafficActivation";
import { handleLiveTtxRoute } from "./liveTtxRoute";
import { handleWildcardRoute } from "./wildcardAdvancement";
import { handleAuditLiteRoute } from "./auditLite";
import { handleRecoveredFunnelApi, isRecoveredPublicRoute, serveRecoveredPublicRoute } from "./funnelRecovery";
import { handleOperatorFulfillmentAgentApi } from "./fulfillmentAgentRoutes";
export { LiveTtxSession } from "./liveSession";

await assertBeaconOnStartup();
await ensureAgentGovernance();

const API_PREFIX = "/api/";

const CATALOG_PATH = "/api/marketplace/catalog";

const AUTH_PREFIX = "/api/auth/";

const ENGINE_PREFIX = "/api/engine/";

const WEBHOOK_PREFIX = "/api/webhooks/";

const SECURITY_PREFIX = "/api/security/";

const TTX_PREFIX = "/api/ttx/";



const RATE_LIMIT_WINDOW_MS = 60_000;

const RATE_LIMIT_MAX_REQUESTS = 60;



const rateLimitBuckets = new Map<string, { count: number; windowStart: number }>();



function isRateLimited(clientId: string): boolean {

  const now = Date.now();

  const bucket = rateLimitBuckets.get(clientId);



  if (!bucket || now - bucket.windowStart >= RATE_LIMIT_WINDOW_MS) {

    rateLimitBuckets.set(clientId, { count: 1, windowStart: now });

    return false;

  }



  bucket.count += 1;

  return bucket.count > RATE_LIMIT_MAX_REQUESTS;

}



export default {

  async fetch(request, env): Promise<Response> {
    // R0 restoration: every request path is guaranteed the standard
    // { error } envelope — an unhandled exception may never escape as a
    // raw platform 500. The structured log line carries no payload data
    // and no secrets; per-route latency/status telemetry stays with
    // recordTelemetrySample.
    try {
      return await handleFetch(request, env);
    } catch (err) {
      console.error(
        JSON.stringify({
          level: "error",
          scope: "worker",
          method: request.method,
          pathname: new URL(request.url).pathname,
          message: err instanceof Error ? err.message : String(err),
        }),
      );
      return Response.json({ error: "Internal error" }, { status: 500 });
    }
  },

} satisfies ExportedHandler<Env>;

async function handleFetch(request: Request, env: Env): Promise<Response> {

    const edgeEnv = env as WorkerEnv;

    const url = new URL(request.url);

    const pathname = url.pathname;

    const mode = resolveSurfaceMode(env);



    if (pathname.startsWith(API_PREFIX)) {

      const apiStarted = Date.now();

      const clientId = request.headers.get("CF-Connecting-IP") ?? "unknown";

      if (isRateLimited(clientId)) {

        return Response.json(

          { error: "Rate limit exceeded — try again shortly" },

          { status: 429, headers: { "Retry-After": String(RATE_LIMIT_WINDOW_MS / 1000) } },

        );

      }



      const betaBlocked = blockAutonomousInBeta(url.pathname, env);

      if (betaBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, betaBlocked.status);
        return betaBlocked;
      }

      const auditLiteResponse = await handleAuditLiteRoute(request, url.pathname, env);

      if (auditLiteResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, auditLiteResponse.status);
        return auditLiteResponse;
      }

      const recoveredFunnelResponse = await handleRecoveredFunnelApi(request, url, env as { TTX_STATE?: KVNamespace });

      if (recoveredFunnelResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, recoveredFunnelResponse.status);
        return recoveredFunnelResponse;
      }



      const operatorAuth = await handleOperatorAuth(request, url.pathname, edgeEnv);

      if (operatorAuth) return operatorAuth;

      const operatorSession = await handleOperatorSession(request, url.pathname, edgeEnv);

      if (operatorSession) return operatorSession;



      const hsxPublic = await handleHsxEdgeRoute(request, url.pathname, edgeEnv);

      if (hsxPublic) return hsxPublic;



      const marketplacePublic = await handleMarketplaceEdgeRoute(request, url.pathname, edgeEnv);

      if (marketplacePublic && url.pathname === "/api/marketplace/session") return marketplacePublic;



      const edgeBlocked = await edgeAuthGate(request, url.pathname, edgeEnv);

      if (edgeBlocked) return edgeBlocked;



      const apiAuthBlocked = await enforceOperatorApiAuth(request, url.pathname, env);

      if (apiAuthBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, apiAuthBlocked.status);
        return apiAuthBlocked;
      }



      const cockpitBlocked = await enforceCockpitSession(
        request,
        env as WorkerEnv & BackboneEnv,
        url.pathname,
      );

      if (cockpitBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, cockpitBlocked.status);
        return cockpitBlocked;
      }



      if (
        url.pathname.startsWith("/api/ttx/local-scenarios") ||
        url.pathname.startsWith("/api/marketplace/purchase")
      ) {
        try {
          const kernelCtx = await resolveEffectiveKernelContext(env as WorkerEnv & BackboneEnv);
          const policyBlocked = enforceGovernancePolicy(url.pathname, request.method, kernelCtx.policy, env);
          if (policyBlocked) {
            await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, policyBlocked.status);
            return policyBlocked;
          }
          const marketBlocked = await enforceMarketplaceGovernance(
            request,
            url.pathname,
            env as WorkerEnv & BackboneEnv,
            kernelCtx.policy,
          );
          if (marketBlocked) {
            await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, marketBlocked.status);
            return marketBlocked;
          }
        } catch {
          // Governance DO unavailable — continue without injection.
        }
      }



      const fedgradeResponse = handleFedGradeRoute(request, url.pathname, env);

      if (fedgradeResponse) return fedgradeResponse;



      const marketplaceProtected = await handleMarketplaceEdgeRoute(request, url.pathname, edgeEnv);

      if (marketplaceProtected) return marketplaceProtected;



      const hsxProtected = await handleHsxEdgeRoute(request, url.pathname, edgeEnv);

      if (hsxProtected) return hsxProtected;



      if (url.pathname === CATALOG_PATH) {

        return serveCatalog(request);

      }



      if (url.pathname.startsWith(ENGINE_PREFIX)) {

        const engineResponse = handleEngineRoute(request, url.pathname, env);

        if (engineResponse) return engineResponse;

      }



      const buildInfoResponse = handleBuildInfoRoute(request, url.pathname, env);

      if (buildInfoResponse) return buildInfoResponse;



      if (url.pathname.startsWith(WEBHOOK_PREFIX)) {

        const webhookResponse = await handleWebhookRoute(request, url.pathname, env);

        if (webhookResponse) return webhookResponse;

      }



      if (url.pathname.startsWith(SECURITY_PREFIX)) {

        const securityResponse = await handleSecurityRoute(request, url.pathname, env);

        if (securityResponse) return securityResponse;

      }

      const wildcardResponse = await handleWildcardRoute(request, url.pathname);

      if (wildcardResponse) return wildcardResponse;

      const fulfillmentOperatorResponse = handleOperatorFulfillmentAgentApi(
        url.pathname,
        request.method.toUpperCase(),
      );

      if (fulfillmentOperatorResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, fulfillmentOperatorResponse.status);
        return fulfillmentOperatorResponse;
      }



      if (url.pathname.startsWith("/api/ttx/live")) {

        const liveResponse = await handleLiveTtxRoute(request, url.pathname, env as WorkerEnv);

        if (liveResponse) return liveResponse;

      }



      if (url.pathname.startsWith(TTX_PREFIX)) {

        const ttxResponse = await handleTtxRoute(request, url.pathname, env);

        if (ttxResponse) return ttxResponse;

      }



      if (url.pathname.startsWith(AUTH_PREFIX)) {

        const authResponse = await handleAuthRoute(request, url.pathname, env);

        if (authResponse) {
          await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, authResponse.status);
          return authResponse;
        }

      }



      const governanceResponse = await handleGovernanceRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (governanceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, governanceResponse.status);
        return governanceResponse;
      }



      const marketplaceBackboneResponse = await handleMarketplaceBackboneRoute(
        request,
        url.pathname,
        env as WorkerEnv & BackboneEnv,
      );

      if (marketplaceBackboneResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, marketplaceBackboneResponse.status);
        return marketplaceBackboneResponse;
      }



      const telemetryResponse = await handleTelemetryRoute(request, url.pathname, env);

      if (telemetryResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, telemetryResponse.status);
        return telemetryResponse;
      }



      const ghostResponse = await handleGhostRoute(request, url.pathname, env);

      if (ghostResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, ghostResponse.status);
        return ghostResponse;
      }

      const usageResponse = await handleUsageRoute(request, url.pathname, env as WorkerEnv);

      if (usageResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, usageResponse.status);
        return usageResponse;
      }

      const flowEventResponse = await handleFlowEventRoute(request, url.pathname, env as WorkerEnv);

      if (flowEventResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowEventResponse.status);
        return flowEventResponse;
      }

      const flowIntelligenceResponse = await handleFlowIntelligenceRoute(request, url.pathname, env as WorkerEnv);

      if (flowIntelligenceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowIntelligenceResponse.status);
        return flowIntelligenceResponse;
      }

      const behaviorResponse = await handleBehaviorIntelligenceRoute(request, url.pathname, env as WorkerEnv);

      if (behaviorResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, behaviorResponse.status);
        return behaviorResponse;
      }

      const experimentationResponse = await handleExperimentationRoute(request, url.pathname, env as WorkerEnv);

      if (experimentationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, experimentationResponse.status);
        return experimentationResponse;
      }

      const trafficActivationResponse = await handleTrafficActivationRoute(request, url.pathname, env as WorkerEnv);

      if (trafficActivationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, trafficActivationResponse.status);
        return trafficActivationResponse;
      }

      const kernelResponse = await handleKernelRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (kernelResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, kernelResponse.status);
        return kernelResponse;
      }

      const healthResponse = await handleHealthRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (healthResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, healthResponse.status);
        return healthResponse;
      }



      const proxied = await proxyToEngine(request, url, env, mode);
      await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, proxied.status);
      return proxied;

    }



    if (isRecoveredPublicRoute(pathname)) {
      const recoveredPublic = await serveRecoveredPublicRoute(request, pathname, env.ASSETS);
      if (recoveredPublic) {
        return recoveredPublic;
      }
    }

    if (mode === "public") {

      return redirectToCanonicalEntry(request);

    }



    const routed = await routeStorefrontSurface(request, pathname, env.ASSETS);

    if (routed) {
      return routed;
    }

    const assetResponse = await env.ASSETS.fetch(request);

    return injectSecurityHeaders(assetResponse);

}



export { GovernanceDO, SessionDO, MarketplaceDO };



function serveCatalog(request: Request): Response {

  if (request.method !== "GET") {

    return Response.json({ error: "Method not allowed" }, { status: 405, headers: { Allow: "GET" } });

  }



  const headers = new Headers({ "Content-Type": "application/json" });

  headers.set("X-Auth-Token-Present", String(request.headers.has("Authorization")));

  const role = request.headers.get("X-Operator-Role");

  const accessLevel = request.headers.get("X-Operator-Access-Level");

  if (role) headers.set("X-Operator-Role-Received", role);

  if (accessLevel) headers.set("X-Operator-Access-Level-Received", accessLevel);



  return new Response(JSON.stringify({ items: CATALOG_ITEMS }), { status: 200, headers });

}



async function proxyToEngine(request: Request, url: URL, env: Env, mode: ReturnType<typeof resolveSurfaceMode>): Promise<Response> {

  if (!env.ENGINE_API_URL) {

    return Response.json({ error: "ENGINE_API_URL is not configured" }, { status: 503 });

  }



  let target: URL;

  try {

    target = new URL(url.pathname + url.search, env.ENGINE_API_URL);

  } catch {

    return Response.json({ error: "ENGINE_API_URL is not a valid URL" }, { status: 500 });

  }



  const upstreamRequest = new Request(target, request);

  upstreamRequest.headers.set("X-Forwarded-Host", url.host);

  upstreamRequest.headers.set("X-Forwarded-Proto", url.protocol.replace(":", ""));



  try {

    const upstreamResponse = await fetch(upstreamRequest);

    const response = new Response(upstreamResponse.body, upstreamResponse);

    response.headers.set("X-Proxied-By", proxyLabel(mode));

    return response;

  } catch (err) {

    return Response.json(

      {

        error: "Engine API unreachable",

        detail: err instanceof Error ? err.message : String(err),

      },

      { status: 502 },

    );

  }

}

