// `Env` is generated by `wrangler types` (npm run cf-typegen) from wrangler.jsonc
// into worker-configuration.d.ts — do not hand-write the binding shape here.

import { CATALOG_ITEMS } from "./catalogData";

const API_PREFIX = "/api/";
const CATALOG_PATH = "/api/marketplace/catalog";

const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX_REQUESTS = 60;

// Best-effort, single-isolate rate limiting only. Cloudflare Workers don't
// share memory across isolates/instances, so under real scale this is a
// basic abuse deterrent, not a hard guarantee. A Durable Object or KV-backed
// limiter would give a real cross-instance guarantee if that's ever needed —
// not added here since it's unjustified for a single-developer storefront.
const rateLimitBuckets = new Map<string, { count: number; windowStart: number }>();

function isRateLimited(clientId: string): boolean {
  const now = Date.now();
  const bucket = rateLimitBuckets.get(clientId);

  if (!bucket || now - bucket.windowStart >= RATE_LIMIT_WINDOW_MS) {
    rateLimitBuckets.set(clientId, { count: 1, windowStart: now });
    return false;
  }

  bucket.count += 1;
  return bucket.count > RATE_LIMIT_MAX_REQUESTS;
}

export default {
  async fetch(request, env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith(API_PREFIX)) {
      const clientId = request.headers.get("CF-Connecting-IP") ?? "unknown";
      if (isRateLimited(clientId)) {
        return Response.json(
          { error: "Rate limit exceeded — try again shortly" },
          { status: 429, headers: { "Retry-After": String(RATE_LIMIT_WINDOW_MS / 1000) } },
        );
      }
      if (url.pathname === CATALOG_PATH) {
        return serveCatalog(request);
      }

      return proxyToEngine(request, url, env);
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;

// First real backend content in this repo — no Engine involved. Pure data,
// no auth enforcement (that's a deliberately separate, later decision), but
// the received auth headers are echoed back as response headers so the
// full SPA -> Worker -> here contract can be verified end-to-end without
// gating access on it.
function serveCatalog(request: Request): Response {
  if (request.method !== "GET") {
    return Response.json({ error: "Method not allowed" }, { status: 405, headers: { Allow: "GET" } });
  }

  const headers = new Headers({ "Content-Type": "application/json" });
  headers.set("X-Auth-Token-Present", String(request.headers.has("Authorization")));
  const role = request.headers.get("X-Operator-Role");
  const accessLevel = request.headers.get("X-Operator-Access-Level");
  if (role) headers.set("X-Operator-Role-Received", role);
  if (accessLevel) headers.set("X-Operator-Access-Level-Received", accessLevel);

  return new Response(JSON.stringify({ items: CATALOG_ITEMS }), { status: 200, headers });
}

async function proxyToEngine(request: Request, url: URL, env: Env): Promise<Response> {
  if (!env.ENGINE_API_URL) {
    return Response.json({ error: "ENGINE_API_URL is not configured" }, { status: 503 });
  }

  let target: URL;
  try {
    target = new URL(url.pathname + url.search, env.ENGINE_API_URL);
  } catch {
    return Response.json({ error: "ENGINE_API_URL is not a valid URL" }, { status: 500 });
  }

  const upstreamRequest = new Request(target, request);
  upstreamRequest.headers.set("X-Forwarded-Host", url.host);
  upstreamRequest.headers.set("X-Forwarded-Proto", url.protocol.replace(":", ""));

  try {
    const upstreamResponse = await fetch(upstreamRequest);
    const response = new Response(upstreamResponse.body, upstreamResponse);
    response.headers.set("X-Proxied-By", "mshops-storefront-worker");
    return response;
  } catch (err) {
    return Response.json(
      {
        error: "Engine API unreachable",
        detail: err instanceof Error ? err.message : String(err),
      },
      { status: 502 },
    );
  }
}
