// `Env` is generated by `wrangler types` (npm run cf-typegen) from wrangler.jsonc

// into worker-configuration.d.ts — do not hand-write the binding shape here.

import { assertBeaconOnStartup } from "../msh-ops/beacon/loadBeacon";
import { ensureAgentGovernance } from "../msh-ops/agent/initAgentGovernance";

import { CATALOG_ITEMS } from "./catalogData";

import { handleAuthRoute } from "./auth";

import { handleEngineRoute } from "./engine";

import { handleBuildInfoRoute } from "./buildInfo";

import { enforceOperatorApiAuth } from "./apiAuth";

import { handleWebhookRoute } from "./webhookTrigger";

import { handleSecurityRoute } from "./security";

import { handleTtxRoute } from "./ttx";

import { edgeAuthGate, handleOperatorAuth, handleOperatorSession } from "./edge/gate";

import { injectSecurityHeaders } from "./edge/headers";

import { handleFedGradeRoute } from "./fedgrade";

import { handleMarketplaceEdgeRoute } from "./marketplaceEdge";

import { handleHsxEdgeRoute } from "./hsxEdge";

import type { WorkerEnv } from "./env";

import { proxyLabel, resolveSurfaceMode, routeStorefrontSurface } from "./surface";
import { redirectToCanonicalEntry } from "./canonical";

import type { BackboneEnv } from "./backboneEnv";
import {
  GovernanceDO,
  handleGovernanceRoute,
  handleMarketplaceBackboneRoute,
  MarketplaceDO,
  SessionDO,
} from "./backbone";
import { handleGhostRoute } from "./ghost";
import { handleHealthRoute } from "./health";
import {
  enforceCockpitSession,
  enforceGovernancePolicy,
  enforceMarketplaceGovernance,
  handleKernelRoute,
  resolveEffectiveKernelContext,
} from "./kernel";
import { blockAutonomousInBeta } from "./mode";
import { handleTelemetryRoute, recordTelemetrySample } from "./telemetry";
import { handleUsageRoute } from "./usage";
import { handleFlowEventRoute } from "./flowRoute";
import { handleFlowIntelligenceRoute } from "./flowIntelligenceRoute";
import { handleFlowExperimentAssignmentRoute, handleFlowExperimentReportRoute } from "./flowExperimentRoute";
import { handleIntentCaptureRoute } from "./intentCaptureRoute";
import { handleIntentQualificationRoute } from "./intentQualificationRoute";
import { handleBehaviorIntelligenceRoute } from "./behaviorRoute";
import { handleExperimentationRoute } from "./experimentationRoute";
import { handleTrafficActivationRoute } from "./trafficActivation";
import { handleActivationRoute } from "./activation/activationRoutes";
import { handleTrafficInteractionRoute } from "./activation/interactionRoute";
import { handleLiveTtxRoute } from "./liveTtxRoute";
import { handleWildcardRoute } from "./wildcardAdvancement";
import { handleAuditLiteRoute } from "./auditLite";
import { handleRecoveredFunnelApi, isRecoveredPublicRoute, redirectWelcomeToRoot, serveRecoveredPublicRoute } from "./funnelRecovery";
import { handleAiGatewayRoute } from "./aiGatewayRoutes";
import { handleOperatorFulfillmentAgentApi } from "./fulfillmentAgentRoutes";
import { handlePrismUiuxRoute } from "./prismUiuxRoutes";
import { handlePrismTriageRoute } from "./prismTriageRoutes";
import { handleBeaconRoute } from "./beaconRoutes";
import { handleOperatorGovernanceRoute } from "./operatorGovernanceRoutes";
import { handleGovernanceProposalRoute } from "./governanceRoutes";
import { handleMcpGovernanceRoute } from "./governance/mcp/routes";
import { handleOperatorAgentsRoute } from "./operatorAgentsRoutes";
export { LiveTtxSession } from "./liveSession";
export { ReceiptAuthority } from "./do/receiptAuthority";

await assertBeaconOnStartup();
await ensureAgentGovernance();

const API_PREFIX = "/api/";

const CATALOG_PATH = "/api/marketplace/catalog";

const AUTH_PREFIX = "/api/auth/";

const ENGINE_PREFIX = "/api/engine/";

const WEBHOOK_PREFIX = "/api/webhooks/";

const SECURITY_PREFIX = "/api/security/";

const TTX_PREFIX = "/api/ttx/";



const RATE_LIMIT_WINDOW_MS = 60_000;

const RATE_LIMIT_MAX_REQUESTS = 60;



const rateLimitBuckets = new Map<string, { count: number; windowStart: number }>();



function isRateLimited(clientId: string): boolean {

  const now = Date.now();

  const bucket = rateLimitBuckets.get(clientId);



  if (!bucket || now - bucket.windowStart >= RATE_LIMIT_WINDOW_MS) {

    rateLimitBuckets.set(clientId, { count: 1, windowStart: now });

    return false;

  }



  bucket.count += 1;

  return bucket.count > RATE_LIMIT_MAX_REQUESTS;

}



export default {

  async fetch(request, env): Promise<Response> {

    const edgeEnv = env as WorkerEnv;

    const url = new URL(request.url);

    const pathname = url.pathname;

    const mode = resolveSurfaceMode(env);



    // #region agent log

    if (

      pathname === "/" ||

      pathname === "/welcome" ||

      pathname === "/login" ||

      pathname === "/marketplace" ||

      pathname.startsWith("/ops/")

    ) {

      console.log("TRACE: PATHNAME =", pathname);

      console.log("TRACE: SURFACE =", mode);

      fetch("http://127.0.0.1:7654/ingest/c1420f4a-f03f-408c-822d-3c63b334f1b9", {

        method: "POST",

        headers: { "Content-Type": "application/json", "X-Debug-Session-Id": "14ea90" },

        body: JSON.stringify({

          sessionId: "14ea90",

          runId: "funnel-primary",

          hypothesisId: "H-entry",

          location: "worker/index.ts:fetch",

          message: "html path entry",

          data: { pathname, mode, method: request.method },

          timestamp: Date.now(),

        }),

      }).catch(() => {});

    }

    // #endregion



    if (pathname.startsWith(API_PREFIX)) {

      const apiStarted = Date.now();

      const clientId = request.headers.get("CF-Connecting-IP") ?? "unknown";

      if (isRateLimited(clientId)) {

        return Response.json(

          { error: "Rate limit exceeded — try again shortly" },

          { status: 429, headers: { "Retry-After": String(RATE_LIMIT_WINDOW_MS / 1000) } },

        );

      }



      const betaBlocked = blockAutonomousInBeta(url.pathname, env);

      if (betaBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, betaBlocked.status);
        return betaBlocked;
      }

      const auditLiteResponse = await handleAuditLiteRoute(request, url.pathname, env);

      if (auditLiteResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, auditLiteResponse.status);
        return auditLiteResponse;
      }

      const recoveredFunnelResponse = await handleRecoveredFunnelApi(request, url, env as { TTX_STATE?: KVNamespace });

      if (recoveredFunnelResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, recoveredFunnelResponse.status);
        return recoveredFunnelResponse;
      }



      const operatorAuth = await handleOperatorAuth(request, url.pathname, edgeEnv);

      if (operatorAuth) return operatorAuth;

      const operatorSession = await handleOperatorSession(request, url.pathname, edgeEnv);

      if (operatorSession) return operatorSession;



      const hsxPublic = await handleHsxEdgeRoute(request, url.pathname, edgeEnv);

      if (hsxPublic) return hsxPublic;



      const marketplacePublic = await handleMarketplaceEdgeRoute(request, url.pathname, edgeEnv);

      if (marketplacePublic && url.pathname === "/api/marketplace/session") return marketplacePublic;



      const edgeBlocked = await edgeAuthGate(request, url.pathname, edgeEnv);

      if (edgeBlocked) return edgeBlocked;



      const apiAuthBlocked = await enforceOperatorApiAuth(request, url.pathname, env);

      if (apiAuthBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, apiAuthBlocked.status);
        return apiAuthBlocked;
      }



      const cockpitBlocked = await enforceCockpitSession(
        request,
        env as WorkerEnv & BackboneEnv,
        url.pathname,
      );

      if (cockpitBlocked) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, cockpitBlocked.status);
        return cockpitBlocked;
      }



      if (
        url.pathname.startsWith("/api/ttx/local-scenarios") ||
        url.pathname.startsWith("/api/marketplace/purchase") ||
        url.pathname.startsWith("/api/ai/marketplace/")
      ) {
        try {
          const kernelCtx = await resolveEffectiveKernelContext(env as WorkerEnv & BackboneEnv);
          const policyBlocked = enforceGovernancePolicy(url.pathname, request.method, kernelCtx.policy, env);
          if (policyBlocked) {
            await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, policyBlocked.status);
            return policyBlocked;
          }
          const marketBlocked = await enforceMarketplaceGovernance(
            request,
            url.pathname,
            env as WorkerEnv & BackboneEnv,
            kernelCtx.policy,
          );
          if (marketBlocked) {
            await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, marketBlocked.status);
            return marketBlocked;
          }
        } catch {
          // Governance DO unavailable — continue without injection.
        }
      }

      const aiGatewayResponse = await handleAiGatewayRoute(
        request,
        url.pathname,
        env as WorkerEnv & BackboneEnv,
      );
      if (aiGatewayResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, aiGatewayResponse.status);
        return aiGatewayResponse;
      }



      const fedgradeResponse = handleFedGradeRoute(request, url.pathname, env);

      if (fedgradeResponse) return fedgradeResponse;



      const marketplaceProtected = await handleMarketplaceEdgeRoute(request, url.pathname, edgeEnv);

      if (marketplaceProtected) return marketplaceProtected;



      const hsxProtected = await handleHsxEdgeRoute(request, url.pathname, edgeEnv);

      if (hsxProtected) return hsxProtected;



      if (url.pathname === CATALOG_PATH) {

        return serveCatalog(request);

      }



      if (url.pathname.startsWith(ENGINE_PREFIX)) {

        const engineResponse = handleEngineRoute(request, url.pathname, env);

        if (engineResponse) return engineResponse;

      }



      const buildInfoResponse = handleBuildInfoRoute(request, url.pathname, env);

      if (buildInfoResponse) return buildInfoResponse;



      if (url.pathname.startsWith(WEBHOOK_PREFIX)) {

        const webhookResponse = await handleWebhookRoute(request, url.pathname, env);

        if (webhookResponse) return webhookResponse;

      }



      if (url.pathname.startsWith(SECURITY_PREFIX)) {

        const securityResponse = await handleSecurityRoute(request, url.pathname, env);

        if (securityResponse) return securityResponse;

      }

      const wildcardResponse = await handleWildcardRoute(request, url.pathname);

      if (wildcardResponse) return wildcardResponse;

      const fulfillmentOperatorResponse = handleOperatorFulfillmentAgentApi(
        url.pathname,
        request.method.toUpperCase(),
      );

      if (fulfillmentOperatorResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, fulfillmentOperatorResponse.status);
        return fulfillmentOperatorResponse;
      }

      const prismTriageResponse = await handlePrismTriageRoute(request, url.pathname, env);

      if (prismTriageResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, prismTriageResponse.status);
        return prismTriageResponse;
      }

      const prismUiuxResponse = await handlePrismUiuxRoute(request, url.pathname, env);

      if (prismUiuxResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, prismUiuxResponse.status);
        return prismUiuxResponse;
      }

      const activationResponse = await handleActivationRoute(request, url.pathname, env as WorkerEnv);

      if (activationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, activationResponse.status);
        return activationResponse;
      }



      if (url.pathname.startsWith("/api/ttx/live")) {

        const liveResponse = await handleLiveTtxRoute(request, url.pathname, env as WorkerEnv);

        if (liveResponse) return liveResponse;

      }



      if (url.pathname.startsWith(TTX_PREFIX)) {

        const ttxResponse = await handleTtxRoute(request, url.pathname, env);

        if (ttxResponse) return ttxResponse;

      }



      if (url.pathname.startsWith(AUTH_PREFIX)) {

        const authResponse = await handleAuthRoute(request, url.pathname, env);

        if (authResponse) {
          await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, authResponse.status);
          return authResponse;
        }

      }



      const governanceResponse = await handleGovernanceRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (governanceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, governanceResponse.status);
        return governanceResponse;
      }



      const marketplaceBackboneResponse = await handleMarketplaceBackboneRoute(
        request,
        url.pathname,
        env as WorkerEnv & BackboneEnv,
      );

      if (marketplaceBackboneResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, marketplaceBackboneResponse.status);
        return marketplaceBackboneResponse;
      }



      const telemetryResponse = await handleTelemetryRoute(request, url.pathname, env);

      if (telemetryResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, telemetryResponse.status);
        return telemetryResponse;
      }



      const ghostResponse = await handleGhostRoute(request, url.pathname, env);

      if (ghostResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, ghostResponse.status);
        return ghostResponse;
      }

      const usageResponse = await handleUsageRoute(request, url.pathname, env as WorkerEnv);

      if (usageResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, usageResponse.status);
        return usageResponse;
      }

      const flowEventResponse = await handleFlowEventRoute(request, url.pathname, env as WorkerEnv);

      if (flowEventResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowEventResponse.status);
        return flowEventResponse;
      }

      const flowIntelligenceResponse = await handleFlowIntelligenceRoute(request, url.pathname, env as WorkerEnv);

      if (flowIntelligenceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowIntelligenceResponse.status);
        return flowIntelligenceResponse;
      }

      const flowExperimentAssignmentResponse = await handleFlowExperimentAssignmentRoute(
        request,
        url.pathname,
        env as WorkerEnv,
      );

      if (flowExperimentAssignmentResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowExperimentAssignmentResponse.status);
        return flowExperimentAssignmentResponse;
      }

      const flowExperimentReportResponse = await handleFlowExperimentReportRoute(
        request,
        url.pathname,
        env as WorkerEnv,
      );

      if (flowExperimentReportResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, flowExperimentReportResponse.status);
        return flowExperimentReportResponse;
      }

      const intentCaptureResponse = await handleIntentCaptureRoute(request, url.pathname, env as WorkerEnv);

      if (intentCaptureResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, intentCaptureResponse.status);
        return intentCaptureResponse;
      }

      const intentQualificationResponse = await handleIntentQualificationRoute(
        request,
        url.pathname,
        env as WorkerEnv,
      );

      if (intentQualificationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, intentQualificationResponse.status);
        return intentQualificationResponse;
      }

      const behaviorResponse = await handleBehaviorIntelligenceRoute(request, url.pathname, env as WorkerEnv);

      if (behaviorResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, behaviorResponse.status);
        return behaviorResponse;
      }

      const experimentationResponse = await handleExperimentationRoute(request, url.pathname, env as WorkerEnv);

      if (experimentationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, experimentationResponse.status);
        return experimentationResponse;
      }

      const trafficActivationResponse = await handleTrafficActivationRoute(request, url.pathname, env as WorkerEnv);

      if (trafficActivationResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, trafficActivationResponse.status);
        return trafficActivationResponse;
      }

      const trafficInteractionResponse = await handleTrafficInteractionRoute(request, url.pathname, env as WorkerEnv);

      if (trafficInteractionResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, trafficInteractionResponse.status);
        return trafficInteractionResponse;
      }

      const beaconResponse = await handleBeaconRoute(request, url.pathname, request.method, env);
      if (beaconResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, beaconResponse.status);
        return beaconResponse;
      }

      const operatorGovernanceResponse = await handleOperatorGovernanceRoute(
        request,
        url.pathname,
        request.method,
        env as WorkerEnv,
      );
      if (operatorGovernanceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, operatorGovernanceResponse.status);
        return operatorGovernanceResponse;
      }

      const governanceProposalResponse = await handleGovernanceProposalRoute(
        request,
        url.pathname,
        request.method,
        env as WorkerEnv,
      );
      if (governanceProposalResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, governanceProposalResponse.status);
        return governanceProposalResponse;
      }

      const mcpGovernanceResponse = await handleMcpGovernanceRoute(
        request,
        url.pathname,
        request.method,
        env as WorkerEnv,
      );
      if (mcpGovernanceResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, mcpGovernanceResponse.status);
        return mcpGovernanceResponse;
      }

      const operatorAgentsResponse = await handleOperatorAgentsRoute(
        request,
        url.pathname,
        request.method,
        env as WorkerEnv,
      );
      if (operatorAgentsResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, operatorAgentsResponse.status);
        return operatorAgentsResponse;
      }

      const kernelResponse = await handleKernelRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (kernelResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, kernelResponse.status);
        return kernelResponse;
      }

      const healthResponse = await handleHealthRoute(request, url.pathname, env as WorkerEnv & BackboneEnv);

      if (healthResponse) {
        await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, healthResponse.status);
        return healthResponse;
      }



      const proxied = await proxyToEngine(request, url, env, mode);
      await recordTelemetrySample(env, url.pathname, Date.now() - apiStarted, proxied.status);
      return proxied;

    }



    if (isRecoveredPublicRoute(pathname)) {
      const recoveredPublic = await serveRecoveredPublicRoute(request, pathname, env.ASSETS);
      if (recoveredPublic) {
        return recoveredPublic;
      }
    }

    const welcomeRedirect = redirectWelcomeToRoot(request, pathname);
    if (welcomeRedirect) {
      return welcomeRedirect;
    }

    if (mode === "public") {

      return redirectToCanonicalEntry(request);

    }



    const routed = await routeStorefrontSurface(request, pathname, env.ASSETS);

    if (routed) {
      return routed;
    }

    const assetResponse = await env.ASSETS.fetch(request);

    return injectSecurityHeaders(assetResponse);

  },

} satisfies ExportedHandler<Env>;



export { GovernanceDO, SessionDO, MarketplaceDO };



function serveCatalog(request: Request): Response {

  if (request.method !== "GET") {

    return Response.json({ error: "Method not allowed" }, { status: 405, headers: { Allow: "GET" } });

  }



  const headers = new Headers({ "Content-Type": "application/json" });

  headers.set("X-Auth-Token-Present", String(request.headers.has("Authorization")));

  const role = request.headers.get("X-Operator-Role");

  const accessLevel = request.headers.get("X-Operator-Access-Level");

  if (role) headers.set("X-Operator-Role-Received", role);

  if (accessLevel) headers.set("X-Operator-Access-Level-Received", accessLevel);



  return new Response(JSON.stringify({ items: CATALOG_ITEMS }), { status: 200, headers });

}



async function proxyToEngine(request: Request, url: URL, env: Env, mode: ReturnType<typeof resolveSurfaceMode>): Promise<Response> {

  if (!env.ENGINE_API_URL) {

    return Response.json({ error: "ENGINE_API_URL is not configured" }, { status: 503 });

  }



  let target: URL;

  try {

    target = new URL(url.pathname + url.search, env.ENGINE_API_URL);

  } catch {

    return Response.json({ error: "ENGINE_API_URL is not a valid URL" }, { status: 500 });

  }



  const upstreamRequest = new Request(target, request);

  upstreamRequest.headers.set("X-Forwarded-Host", url.host);

  upstreamRequest.headers.set("X-Forwarded-Proto", url.protocol.replace(":", ""));



  try {

    const upstreamResponse = await fetch(upstreamRequest);

    const response = new Response(upstreamResponse.body, upstreamResponse);

    response.headers.set("X-Proxied-By", proxyLabel(mode));

    return response;

  } catch (err) {

    return Response.json(

      {

        error: "Engine API unreachable",

        detail: err instanceof Error ? err.message : String(err),

      },

      { status: 502 },

    );

  }

}

