name: CI

on:
  push:
  pull_request:

jobs:
  typecheck-test-build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      BUILD_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      NPM_CONFIG_SCRIPT_SHELL: cmd.exe
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run typecheck

      - run: npm test

      - run: npm run build
